---
- hosts: cvp
  gather_facts: no
  connection: local
  vars:
    username: cvpadmin
    password: cvp123
    protocol: http

  tasks:
    - name: Provision Server
      cv_server_provision:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        protocol: "{{ protocol }}"
        server_name: "mattserver"
        switch_name: "ansible-192.168.1.21"
        switch_port: "4"
        template: "host_template_a.j2"
        state: "add"
        auto_run: True
