---
- hosts: cvp
  gather_facts: no
  connection: local

  tasks:
    - name: Gather info from cvp
      cv_info:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        protocol: "{{ protocol }}"

    - name: Gather inventory
      cv_inventory:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        protocol: "{{ protocol }}"

    - name: Gather Containers
      cv_container:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        protocol: "{{ protocol }}"
        container: "test"
