cvp_host:
    - '<cvp host>'
cvp_user: <username>
cvp_pw: <password>
target_container: Ansible
provisioned_container: Provisioned
image: '<image bundle name>'
gw: '<default gateway address>'
subnet_mask: <subnet mask prefix len>

